version: "3.3"
services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      PGDATA: /var/lib/postgresql/data/pgdata
  play:
    build:
      context: .
    ports:
      - ${PORT}:9000
    environment:
      - DB_USER
      - DB_PASS
      - DB_HOST
      - SECRET_KEY
volumes:
  dbdata:
